### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by zhamri** [STIW2024/Main-Issues#1]
Write a program using `JSP` to display the following output:

```
Hello World
STIW2024 Software Engineering
```

**Comment by thiviya** [comment]
<%-- 
    Document   : index
    Created on : Nov 21, 2017, 5:17:28 PM
    Author     : thiviya
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World</h1>
        <h1>STIW2024 Software Engineering</h1>
    </body>
</html>

**Comment by zhamri** [comment]
put your screenshot at the bottom

**Comment by NgZhengYi** [comment]
CODE :
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
Hello World
<br>
STIW2024 Software Engineering
</body>
</html>

![image](https://user-images.githubusercontent.com/33797234/33065537-1d055000-cee4-11e7-96a4-39ca70384c7c.png)

![image](https://user-images.githubusercontent.com/33797234/33064933-54577364-cee2-11e7-9b5e-4398226b0022.png)

**Comment by Aman748** [comment]
## Code :
```jsp
<%-- 
    Document   : index
    Created on : 2017-11-21, 18:52:33
    Author     : Aman
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Issue #1 Hello World</title>
    </head>
    <body>
        <div>Hello World</div>
        <div>STIW2024 Software Engineering</div>
    </body>
</html>
```
## Output :
![se-issue 1_output](https://user-images.githubusercontent.com/15071303/33065079-cb8d2bea-cee2-11e7-9838-07cb7f0eddc9.png)

**Comment by ezzat787** [comment]
CODE:
![mmmmm](https://user-images.githubusercontent.com/33803723/33065376-a3749c96-cee3-11e7-8644-5c91b3e44c1a.PNG)

OUTPUT
![image](https://user-images.githubusercontent.com/33803723/33065440-ca8f8642-cee3-11e7-9c68-08e30fe71016.png)

REFERENCE
http://www.c-sharpcorner.com/UploadFile/fd0172/how-to-create-jsp-web-page-in-netbeans-ide-7-4-using-tomcat/

**Comment by JohnWick27** [comment]
```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Hello World </title>
    </head>
    <body>
        <left>
       
       <h1 style="color:blue;">Hello World</h1>
       <h3 style="color:red;">STIW2024 Software Engineering</h3>
       
        </left>
    </body>
</html>
```
![hello](https://user-images.githubusercontent.com/26071478/33066541-858767a6-cee6-11e7-8ae4-4535f02ec29b.PNG)

**Comment by zhamri** [comment]
good reference

**Comment by yaopeng96** [comment]
![picture1](https://user-images.githubusercontent.com/33802685/33069296-0dbbd640-ceef-11e7-971f-5d9c8c93f632.png)
![picture2](https://user-images.githubusercontent.com/33802685/33069297-0e75c71c-ceef-11e7-93da-d23fcef700b1.png)

**Comment by zhenkit1996** [comment]
<%-- 
    Document   : index
    Created on : Nov 21, 2017, 8:09:41 PM
    Author     : aspire
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <font size="10" color="red"><%="Hello World!" %></font>
        <br>
        <font size="20" color="blue"><%="STIW2024 SOFTWARE ENGINEERING" %></font>
        <body bgcolor="green">

    </body>
</html>
![jsp](https://user-images.githubusercontent.com/33799522/33072664-6535067e-cefb-11e7-9497-3740eaefb393.png)

**Comment by kzkit** [comment]
# CODE : 
```
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <font size="10" color="red"><%="Hello World" %></font>
        <br>
        <font size="20" color="blue"><%="STIW2024 Software Engineering" %></font>
        <body bgcolor="green">

    </body>
</html>

```
![jsp](https://user-images.githubusercontent.com/33799522/33073327-8946f9e4-cefd-11e7-8f36-dca8e4a979fe.png)

**Comment by jairam0905** [comment]
![helloworld](https://user-images.githubusercontent.com/33801250/33074151-150796c6-cf00-11e7-83bb-b9d7addb8755.png)

**Comment by AriffAziz94** [comment]
![image](https://user-images.githubusercontent.com/33802898/33075583-fd801d66-cf04-11e7-8e6a-3d4f4e229842.png)

**Comment by Koksheng** [comment]
![jsp helloworld](https://user-images.githubusercontent.com/33799735/33076913-23989f74-cf09-11e7-938c-18c80760dfa9.PNG)
