### ISSUE TITLE
Hello World 2

### ISSUE THREAD

**Issue by zhamri** [STIW2024/Main-Issues#2]
Write a program using `Servlets` to display the following output:

```
Hello World
STIW2024 Software Engineering
```

**Comment by jairam0905** [comment]
![1](https://user-images.githubusercontent.com/33801250/33079604-0597d384-cf11-11e7-91c6-19e93d4f4eda.png)
![2](https://user-images.githubusercontent.com/33801250/33079605-05ec207e-cf11-11e7-9e41-88f127a7085c.png)
![helloworld2](https://user-images.githubusercontent.com/33801250/33079607-062b4498-cf11-11e7-9b38-d40f9d656843.png)

**Comment by jairam0905** [comment]
References.
https://www.youtube.com/results?search_query=how+to+display+code+in+new+window+from+netbeans

**Comment by jairam0905** [comment]
Reference.
https://www.youtube.com/watch?v=HAg77OnM55Y

**Comment by Nurzyra** [comment]
![1](https://user-images.githubusercontent.com/33803299/33080163-650798f8-cf12-11e7-8d1f-c21a393b51b8.gif)

![2](https://user-images.githubusercontent.com/33803299/33080181-6d3939e6-cf12-11e7-96fc-41ff3241e654.gif)


![3](https://user-images.githubusercontent.com/33803299/33080202-723c1b2a-cf12-11e7-9211-d96dda2cfedb.gif)


![4](https://user-images.githubusercontent.com/33803299/33080212-78c60776-cf12-11e7-9e27-39c272434e7e.gif)

![5](https://user-images.githubusercontent.com/33803299/33080227-7f28a8c6-cf12-11e7-8140-6859a6f4aa55.gif)

**Comment by Nurzyra** [comment]
References:
http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by Nurzyra** [comment]
References:
https://www.javatpoint.com/creating-servlet-in-netbeans-ide
http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by ezzat787** [comment]
code:
![1](https://user-images.githubusercontent.com/33803723/33080846-01ae97be-cf14-11e7-8f31-ea2848a88736.PNG)
![2](https://user-images.githubusercontent.com/33803723/33080853-04fb6406-cf14-11e7-9078-f9fb7a642e60.PNG)
![4](https://user-images.githubusercontent.com/33803723/33080857-06b6bf2a-cf14-11e7-9a75-c5f1a5480cc3.PNG)

output:
![image](https://user-images.githubusercontent.com/33803723/33080935-2f8b0b86-cf14-11e7-8320-4f53751a1ce3.png)
![image](https://user-images.githubusercontent.com/33803723/33080950-39565eae-cf14-11e7-9606-5388da40507f.png)

reference:
https://www.ntu.edu.sg/home/ehchua/programming/java/JavaServlets.html
https://www.javatpoint.com/creating-servlet-in-netbeans-ide

**Comment by kzkit** [comment]
HTML 
![servlet1](https://user-images.githubusercontent.com/33799522/33081490-76dc47ec-cf15-11e7-9618-9518383a4df2.png)
XML
![servlet2](https://user-images.githubusercontent.com/33799522/33081494-79338b36-cf15-11e7-89d3-bf99c304c343.png)
Servlet.java
![servlet3](https://user-images.githubusercontent.com/33799522/33081498-7a6f6c4a-cf15-11e7-9f46-ceb0d0c0bc0a.png)
Output
![servlet4](https://user-images.githubusercontent.com/33799522/33081500-7bf7b16c-cf15-11e7-8aea-3c79835c92bb.png)
Output
![servlet5](https://user-images.githubusercontent.com/33799522/33081503-7d46a8ac-cf15-11e7-901f-5c1b984dc227.png)

**Comment by Koksheng** [comment]
![servlet1](https://user-images.githubusercontent.com/33799735/33081902-5c705ab4-cf16-11e7-844a-5b4edac53499.PNG)

**Comment by Koksheng** [comment]
![servlet2](https://user-images.githubusercontent.com/33799735/33081924-6ee35a02-cf16-11e7-9121-9f521cc6458d.PNG)

**Comment by Koksheng** [comment]
![servlet3](https://user-images.githubusercontent.com/33799735/33082142-0069427a-cf17-11e7-8771-ebb9dd57b7ec.PNG)

**Comment by Aman748** [comment]
## Code :
```java
package Issue2;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Aman
 */
@WebServlet(name = "Issue2", urlPatterns = {"/Issue2"})
public class Issue2 extends HttpServlet {
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Issue2 Servlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<div>Hello World</div>");
            out.println("<div>STIW2024 Software Engineering</div>");
            out.println("</body>");
            out.println("</html>");
        }
    }
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }

}
```
## Output :
![se-issue 2_output](https://user-images.githubusercontent.com/15071303/33081948-857cd400-cf16-11e7-9296-0f2d99c5d09b.png)

**Comment by thiviya** [comment]
![1](https://user-images.githubusercontent.com/33799647/33082459-d2885a34-cf17-11e7-9ec3-affc4e5dedc0.png)
![2](https://user-images.githubusercontent.com/33799647/33082474-dad559bc-cf17-11e7-9f6d-98d9dc6bb127.png)
![3](https://user-images.githubusercontent.com/33799647/33082484-e158e42a-cf17-11e7-986a-e8d09d804842.png)
![4](https://user-images.githubusercontent.com/33799647/33082487-e2abc720-cf17-11e7-875c-769af113101f.png)
![5](https://user-images.githubusercontent.com/33799647/33082489-e3c8acae-cf17-11e7-8db4-03bb16220f25.png)







reference 
http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by nadiahnaz** [comment]
![servlet_myservlet](https://user-images.githubusercontent.com/33803371/33082437-bc212ad2-cf17-11e7-9bc7-b935d67b6fc6.JPG)
![servlet_index_html](https://user-images.githubusercontent.com/33803371/33082445-c4549450-cf17-11e7-84b5-4bb9afd75854.JPG)
![servlet_web_xml](https://user-images.githubusercontent.com/33803371/33082451-cc773f7a-cf17-11e7-8818-3c381dd5e72e.JPG)
![servlet_web_browser_01](https://user-images.githubusercontent.com/33803371/33082488-e3ad9932-cf17-11e7-8a7a-ee2890bbefd9.JPG)
![servlet_web_browser_02](https://user-images.githubusercontent.com/33803371/33082495-e77fca12-cf17-11e7-8f2d-be6f8a45f12a.JPG)

reference:
http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by JohnWick27** [comment]
# web.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
    <servlet>
        <servlet-name>hello1</servlet-name>
        <servlet-class>NewServlet1</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>hello1</servlet-name>
        <url-pattern>/hello1</url-pattern>
    </servlet-mapping>
    <session-config>
        <session-timeout>
            30
        </session-timeout>
    </session-config>
    <welcome-file-list>
  <welcome-file>newhtml1.html</welcome-file> 
  </welcome-file-list>
</web-app>
```
# newhtml1.html
```
<html>
    <head>
        <title>Hello World!</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1>
        <div>Hello World</div>
        <div>STIW2024 Software Engineering</div></h1>
    </body>
</html>
```

# NewServlet1.java

```
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Azimjon Khamdamov
 */
public class NewServlet1 extends HttpServlet {

    
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet NewServlet1</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet NewServlet1 at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    

}
```

![servlet](https://user-images.githubusercontent.com/26071478/33083278-ea971726-cf19-11e7-801c-b464eadaf4da.PNG)


Reference: http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by Lilinhong123** [comment]
`package com.runoob.test;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Helloservlet
 */
@WebServlet("/Helloservlet")
public class Helloservlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Helloservlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		 response.setCharacterEncoding("GBK");
	        response.getWriter().write("Hello world!\n");
	        response.getWriter().write("STIW2024 Software Engineering");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		 doGet(request, response);
	}

}`

![1](https://user-images.githubusercontent.com/33807128/33084613-5cc7ae02-cf1d-11e7-90a7-d807c6f71e97.png)
![2](https://user-images.githubusercontent.com/33807128/33084624-619e435a-cf1d-11e7-8320-31f7b24deabd.png)

**Comment by NgZhengYi** [comment]
import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class HelloWorldServlet
 */
@WebServlet("/HelloWorldServlet")
public class HelloWorldServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public HelloWorldServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		PrintWriter print = response.getWriter();
		response.getWriter().append("Served at: ").append(request.getContextPath());
		
		print.println("<html><body>");
		print.println("Hello World <br> STIW2024 Software Engineering");		
		print.println("</html></body>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

![image](https://user-images.githubusercontent.com/33797234/33085079-9b3feb76-cf1e-11e7-8d2f-fead1947710d.png)

**Comment by AriffAziz94** [comment]
package testing;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class HelloWorld
 */
@WebServlet("/HelloWorld")
public class HelloWorld extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public HelloWorld() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		out.println("Hello World!!!");
		out.println("STIW2024  Software Engineering");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

![image](https://user-images.githubusercontent.com/33802898/33085325-5d55a89a-cf1f-11e7-942a-721fb5ff7ce6.png)

**Comment by YangYifei666** [comment]
```java
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = {"/HelloWorld2"})
public class HelloWorld2 extends HttpServlet {

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet HelloWorld2</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Hello World</h1>");
            out.println("<h1>STIW2024 Software Engineerin</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }

}

```
![image](https://user-images.githubusercontent.com/33801634/33089015-5bcc6fb2-cf2a-11e7-902a-8303ed4ddf7e.png)

**Comment by ChoyCheeWei** [comment]
![1](https://user-images.githubusercontent.com/33800659/33087704-4fb0d294-cf26-11e7-86ea-1960b0d04022.JPG)
![2](https://user-images.githubusercontent.com/33800659/33087705-4ff09faa-cf26-11e7-833b-f8c1aa9d6b25.JPG)
![3](https://user-images.githubusercontent.com/33800659/33087706-5030060e-cf26-11e7-94cb-115b5b9e0f04.JPG)
![4](https://user-images.githubusercontent.com/33800659/33087707-506a3da6-cf26-11e7-8747-2b5ad028ab4c.JPG)
![5](https://user-images.githubusercontent.com/33800659/33087708-50a7656e-cf26-11e7-8e1b-7ab69330ae5f.JPG)
reference : http://www.studytonight.com/servlet/creating-servlet-in-netbeans.php

**Comment by yaopeng96** [comment]
![picture1](https://user-images.githubusercontent.com/33802685/33088933-183b03bc-cf2a-11e7-9e49-39bcd69fe971.png)
![picture2](https://user-images.githubusercontent.com/33802685/33088934-1873a208-cf2a-11e7-803c-0f54ab80edb0.png)
![picture3](https://user-images.githubusercontent.com/33802685/33088935-18ac8528-cf2a-11e7-84e7-2e011fe095fc.png)

**Comment by kopilim96** [comment]
![image](https://user-images.githubusercontent.com/33795389/33091313-b1b5d8bc-cf31-11e7-96fb-e3acde366c0a.png)
![image](https://user-images.githubusercontent.com/33795389/33091352-d493431a-cf31-11e7-9ff2-208310f35ecd.png)

**Comment by kopilim96** [comment]
![image](https://user-images.githubusercontent.com/33795389/33091376-e7f91c54-cf31-11e7-8ce3-6f4033481c1a.png)
![image](https://user-images.githubusercontent.com/33795389/33091384-efd30e80-cf31-11e7-8ab0-c1b72df26c40.png)

Reference :- https://www.youtube.com/watch?v=JGwWNGJdvx8

**Comment by yeepheng96** [comment]
![screenshot 2017-11-22 17 40 40](https://user-images.githubusercontent.com/33802800/33120365-d1ffcb98-cfac-11e7-949f-3cc69109ab5a.png)
![screenshot 2017-11-22 17 41 08](https://user-images.githubusercontent.com/33802800/33120372-d572aa3e-cfac-11e7-8cbd-9f340d56ceb3.png)
![screenshot 2017-11-22 17 41 15](https://user-images.githubusercontent.com/33802800/33120375-d95d7fc0-cfac-11e7-9f54-6331a522cc18.png)
![screenshot 2017-11-22 17 41 32](https://user-images.githubusercontent.com/33802800/33120381-dc74fb52-cfac-11e7-8daa-5fca0c3b1a9e.png)
![screenshot 2017-11-22 17 41 41](https://user-images.githubusercontent.com/33802800/33120387-df392124-cfac-11e7-97b5-9c90523e8f53.png)

References:
https://www.javatpoint.com/creating-servlet-in-netbeans-ide
https://www.tutorialspoint.com/html/html_basic_tags.htm

**Comment by LoiTongFong** [comment]
![hw1](https://user-images.githubusercontent.com/33795443/33120504-366e94ce-cfad-11e7-9c3e-00cf5768ead3.JPG)
![hw2](https://user-images.githubusercontent.com/33795443/33120603-8ba57002-cfad-11e7-8009-fb2dbfced265.JPG)
![hw3](https://user-images.githubusercontent.com/33795443/33120608-90ff1508-cfad-11e7-986c-217bba54e51b.JPG)

References:
https://www.youtube.com/watch?v=HAg77OnM55Y
https://www.youtube.com/watch?v=KJhDGYWgzTc
